### PR TITLE
- Remove duplicate translation file. It creates multiple key entries in ...

### PR DESCRIPTION
**Pull request by heliocastro**
...desktop files.

Signed-off-by: Helio Chissini de Castro <helio@kde.org>

### CODE REVIEW

**Comment by luis-pereira** [comment]
@heliocastro Russian translators are providing ru and ru_RU translations (in some cases the same one). IMO changing the wrong ru to ru_RU is the thing to do right now.

**Comment by paulolieuthier** [comment]
@heliocastro what do you think?

**Comment by paulolieuthier** [comment]
@heliocastro ping.

**Comment by jleclanche** [comment]
@luis-pereira is right.

**Pull request closed without merging**
