### PR TITLE
Handle clicks on text labels properly (workaround for QTBUG-49025)

### PR DESCRIPTION
**Pull request by mickael9**
See PR #40 for the original problem.

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Just tested it. After hovering a link, `linkHovered` is emitted when first hovering another part of the label which is not a link. so it works as very well. Clicking the link doesn't work, but that's how master is as well. After adopting the new `connect` syntax, GTM.

**Comment by mickael9** [comment]
I used the old SIGNAL()/SLOT() syntax because that's what is used currently. I can add another commit and switch every connect in the project to the new syntax if you want.

**Comment by paulolieuthier** [comment]
We're in a transition. Got ahead, and thanks a lot.

**Comment by mickael9** [comment]
Done

> Clicking the link doesn't work, but that's how master is as well.

What do you mean ? Clicking links works fine for me with master.

**Comment by paulolieuthier** [comment]
You mean the browser opens the page?

**Comment by mickael9** [comment]
Yes

**Pull request merged**
