### PR TITLE
Fix image format for images with 3 channels

### PR DESCRIPTION
**Pull request by hluk**
Fixes corrupted notification icon for Spotify desktop application
which uses deprecated "icon_data" hint with 3-channel image data.

### CODE REVIEW

**Comment by jleclanche** [comment]
Uh this may fix the spotify icon but it will break other images.

**Comment by hluk** [comment]
It shouldn't break other images -- the previous behavior is still there (though I'm not sure why the `QImage::rgbSwapped()` is needed).

Spotify sends image data with only 3 channels per pixel (no alpha channel). So image format is definitely not ARGB32. Well, more correct solution could be something like:
```
    if (hasAlpha && channels == 4 && bitsPerSample == 8)
        imageFormat = QImage::Format_ARGB32;
    else if (!hasAlpha && channels == 4 && bitsPerSample == 8)
        imageFormat = QImage::Format_RGB32;
    else if (!hasAlpha && channels == 3 && bitsPerSample == 6)
        imageFormat = QImage::Format_RGB666;
    else if (!hasAlpha && channels == 3 && bitsPerSample == 5)
        imageFormat = QImage::Format_RGB555;
    else if (!hasAlpha && channels == 3 && bitsPerSample == 8)
        imageFormat = QImage::Format_RGB888;
    else if (!hasAlpha && channels == 3 && bitsPerSample == 4)
        imageFormat = QImage::Format_RGB444;
    else
        imageFormat = QImage::Format_RGB16;
```

**Comment by jleclanche** [comment]
Sounds like the spotify image is broken, not what we're doing, to be honest

**Comment by hluk** [comment]
It doesn't seem broken. Spotify tells notification daemon exactly how to process the image data for notification and sends correct data (`QImage` doesn't have any problems parsing the pixels).

**Comment by jleclanche** [comment]
@surlykke @luis-pereira either of you can give this a second look?

**Comment by hluk** [comment]
To be more specific: The problem is not that Spotify uses deprecated hint "icon_data". It could as well use "image_data" with same data. But AFAIK application can choose different image formats.

Also it seems that any client application can crash `lxqt-notificationd` because it sends incorrect image data. I.e. the size of image data is not checked when pointer to data is passed to `QImage`.

**Comment by paulolieuthier** [comment]
@hluk could you please provide a 3-channel image example? I downloaded spotify's tarball and tested with its icon and it worked. I also created a grayscale icon with no transparency and it also worked.

**Comment by hluk** [comment]
Can you try playing some music in Spotify? The album art seems to be reencoded by Spotify before it's sent to notification daemon (on play or resume). I just tested it and it's still an issue in master branch.

**Comment by paulolieuthier** [comment]
Ah, so it's the album art, not the app's icon. I never used Spotify, but I'll try it.

**Comment by paulolieuthier** [comment]
OK, now I can see that the fix works for the image being displayed. The only problem I'm having is that all spotify's noifitications balloons display the same album art, which is the first one I played after opening spotify. But I guess this is another bug.

@hluk can you reproduce it as well?

**Comment by hluk** [comment]
Nope, seem to be working fine. Could be Spotify issue (I tested with version 0.9.17.1.g9b85d436).

**Comment by paulolieuthier** [comment]
@hluk please rebase your branch.

**Comment by hluk** [comment]
Rebased.

**Comment by paulolieuthier** [comment]
Thanks!

**Pull request merged**
