### PR TITLE
Update and rename lxqt-config-notificationd_fr_FR.desktop

### PR DESCRIPTION
**Pull request by paiiou**
Update and rename lxqt-config-notificationd_fr_FR.desktop to lxqt-config-notificationd_fr.desktop

### CODE REVIEW

**Comment by pmattern** [comment]
Strictly speaking you didn't translate string "LXQt" in key `GenericName`. But honestly I'm not that sure whether it makes sense in the template in the first place.
So probably we should just merge this PR and discuss whether we scrub LXQt from this key in general sometime / -where else.
@palinek Thoughts?

**Comment by palinek** [comment]
Actualy, I think all components should mention LXQt in their corresponding .desktop files to not pretend they are some "universal" tools.

**Comment by pmattern** [comment]
Meanwhile I remembered I had made an attempt to discuss this problem quite a while ago in lxde/lxqt#713 anyway.
So @paiiou could you please include string "LXQt" in key `GenericName` of lxqt-config-notificationd_fr.desktop somehow for the time being? This should be doable the same way as we've discussed in lxde/lxqt-l10n#159.

**Comment by paiiou** [comment]
I modified directly in my GitHub fork
I am sorry. I did not realize the consequences of this simplification.

**Comment by pmattern** [comment]
Sure enough I've missed something. In order to be consistent with the template it would be good if you could put key `Comment` as activity. Maybe something like "Configurer les notifications du bureau LXQt".

Also, you've added another commit to fix that "string LXQt" thing which doesn't make sense. You could run `git rebase -i HEAD~2` and follow the instructions to get rid of the superfluous commit.
But this is only if you still want to go through some Git exercise. Otherwise we can squash the commit on behalf of you as well, as always preserving your authorship.

**Comment by paiiou** [comment]
I think I'm starting to saturate for today
Merci

**Comment by palinek** [comment]
squashed and landed in @aea99dd, thanks

**Pull request closed without merging**
